import { Head } from "next/head";
import peopleJson from "../../libs/people-data";
import { useRouter } from "next/router";

export default function People() {
  const router = useRouter();
  const handleOnClick = (guid) => {
    router.push(`/people/${guid}`);
  };
  return (
    <>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>People</h1>
        <>
          {peopleJson.map(({ guid, name }) => {
            return (
              <h2 key={guid} onClick={() => handleOnClick(guid)}>
                {name}
              </h2>
            );
          })}
        </>
      </main>

      <footer>
        <p>Made with ❤</p>
      </footer>
    </>
  );
}
